force-app/main/default/objects/EburyTradeSettings__c/EburyTradeSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ebury Trade Settings</label>
</CustomObject>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{000000}</displayFormat>
        <label>Trade Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <description>Amount of the buy currency the customers wants to buy</description>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Currency the customer wants to buy</description>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>Conversation rate from sell currency into buy currency</description>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Amount of the sell currency the customers wants to sell</description>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Currency the customer wants to sell</description>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <description>List of currencies</description>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewTradeController.cls
public with sharing class NewTradeController {

    @AuraEnabled
    public static ActionResponse.Response getRate(String sellCurrency, String buyCurrency) {

        RateResponse rateResponse;

        EburyTradeSettings__c tradeSettings = EburyTradeSettings__c.getInstance('Default');
        String apiKey = tradeSettings.ApiKey__c;
            
        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        request.setEndpoint('callout:GetLatestExchangeRate'+'/latest?symbols=' + buyCurrency + '&base=' + sellCurrency);
        request.setHeader('apikey', apiKey);
        request.setTimeout(20000);
        Http http = new Http();
        
        try {
            HttpResponse response = http.send(request);

            if(response.getStatusCode() >= 200 && response.getStatusCode() < 300) {
                
                Map<String, Object> resultMap  = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                Map<String, Object> ratesMap   = (Map<String, Object>) resultMap.get('rates');
                rateResponse = new RateResponse(ratesMap, buyCurrency);

                ActionResponse.Response responseRate = new ActionResponse.Response(
                    false, '', JSON.serialize(rateResponse)
                );
                return responseRate;

            } else {
                throw new CalloutException('CalloutException: ' + response.getBody());
            }

        } catch (Exception e) {
            return new ActionResponse.Response(e);
        }

    }

    @AuraEnabled
    public static ActionResponse.Response createNewTrade(String tradeInfoJSON){

        try {
            TradeInfo info = (TradeInfo)JSON.deserialize(tradeInfoJSON, TradeInfo.class);

            Trade__c trade = new Trade__c (
                Sell_Currency__c    = info.SellCurrency, 
                Buy_Currency__c     = info.BuyCurrency, 
                Sell_Amount__c      = info.SellAmount,
                Buy_Amount__c       = info.BuyAmount, 
                Rate__c             = info.Rate
            );
            insert trade;

            ActionResponse.Response tradeResponse = new ActionResponse.Response(
                false, 'Trade Created', JSON.serialize(trade)
            );
            return tradeResponse;
            
        } catch (Exception e) {
            return new ActionResponse.Response(e);
        }
    }


    public class RateResponse {
        @AuraEnabled public String  Base      {get; set;} 
        @AuraEnabled public Boolean Success   {get; set;}
        @AuraEnabled public Decimal TimeStamp {get; set;}
        @AuraEnabled public Date    DateRate  {get; set;} 
        @AuraEnabled public Decimal Rate      {get; set;}

        public RateResponse () {}

        public RateResponse (Map<String, Object> ratesMap, String buyCurrency) {
            this.Rate   = (Decimal)ratesMap.get(buyCurrency);
        }  
    }

    public class TradeInfo {
        @AuraEnabled public String  SellCurrency {get; set;} 
        @AuraEnabled public String  BuyCurrency  {get; set;}  
        @AuraEnabled public Decimal SellAmount   {get; set;}   
        @AuraEnabled public Decimal BuyAmount    {get; set;} 
        @AuraEnabled public Decimal Rate         {get; set;} 

        public TradeInfo () {}
    }

}