force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{000000}</displayFormat>
        <label>Trade Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <description>Amount of the buy currency the customers wants to buy</description>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Currency the customer wants to buy</description>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>Conversation rate from sell currency into buy currency</description>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Amount of the sell currency the customers wants to sell</description>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Currency the customer wants to sell</description>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>List of currencies</description>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewTradeControllerTest.cls
@isTest
public with sharing class NewTradeControllerTest {
    
    @TestSetup
    static void makeData(){
        
        List<Trade__c> newTrades = new List<Trade__c>();

        Trade__c tradeEUR = new Trade__c (
            Sell_Currency__c    = 'EUR',
            Buy_Currency__c     = 'USD',
            Sell_Amount__c      = 1000,
            Buy_Amount__c       = 1000 * 1.253,
            Rate__c             = 1.253
        );
        newTrades.add(tradeEUR);

        Trade__c tradeUSD = new Trade__c (
            Sell_Currency__c    = 'USD',
            Buy_Currency__c     = 'EUR',
            Sell_Amount__c      = 1500,
            Buy_Amount__c       = 1500 * 0.398,
            Rate__c             = 0.398
        );
        newTrades.add(tradeUSD);

        Trade__c tradeGBP = new Trade__c (
            Sell_Currency__c    = 'GBP',
            Buy_Currency__c     = 'EUR',
            Sell_Amount__c      = 2500,
            Buy_Amount__c       = 2500 * 1.458,
            Rate__c             = 1.458
        );
        newTrades.add(tradeGBP);

        insert newTrades;
    }

    @isTest
    public static void createNewTradeSuccessTest() {
       
        Test.startTest();
        
           Trade__c trade = [
             SELECT Buy_Amount__c, Buy_Currency__c, 
                    Rate__c, Sell_Amount__c, Sell_Currency__c
               FROM Trade__c 
              WHERE Sell_Currency__c IN ('USD', 'GBP', 'EUR')
              LIMIT 1
            ];

            String tradeInfoJSON =  JSON.serialize(trade);

            ActionResponse.Response response = NewTradeController.createNewTrade(tradeInfoJSON);
            System.assertEquals(response.HasError, false);
            
        Test.stopTest();
    }

    @isTest
    public static void createNewTradeErrorTest() {
        
        Test.startTest();

            try {
                ActionResponse.Response response = NewTradeController.createNewTrade(null);
                System.assertEquals(response.HasError, true);
            } catch (Exception e) {
                System.debug('Error: ' + e.getMessage());
            }
            
        Test.stopTest();
    }
}